package com.example.demo.controller;

import com.example.demo.Model.GameUser;
import com.example.demo.Model.Repository;
import com.example.demo.Model.Response;
import com.example.demo.service.Numbers;
import lombok.Getter;
import lombok.Setter;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.web.bind.annotation.*;

import java.util.List;

@Getter
@Setter
@RestController
public class Controller {
    public static Numbers randomNumbers = new Numbers();
    //@Autowired // This means to get the bean called userRepository
    // Which is auto-generated by Spring, we will use it to handle the data
    @Autowired
    private Repository repository;

    @CrossOrigin
    @PostMapping(path="/add") // Map ONLY POST Requests
    public @ResponseBody String addNewUser (@RequestBody Response response) {

        GameUser newRecord = new GameUser();
        newRecord.setUsername(response.getUsername());
        newRecord.setAttemptid(newRecord.getAttemptid() + 1);
        newRecord.setYou_entered(response.getYou_entered());


        Integer multiplicaton = response.getNum1() * response.getNum2();
        System.out.println("you_entered : " + response.getYou_entered());
        System.out.println("multiplication" + multiplicaton);
        newRecord.setMultiplication(multiplicaton);
        if(newRecord.getYou_entered().equals(newRecord.getMultiplication()))
            newRecord.setCorrectOrNot("Yes");
        else
            newRecord.setCorrectOrNot("No");
        repository.save(newRecord);
        return "Saved";
    }

    @CrossOrigin
    @GetMapping(path="/randomnumbers")
    public Numbers index() {
        return randomNumbers.getRandomNumbers();
    }

    @CrossOrigin
    @GetMapping(path="/stats")
    public @ResponseBody
    List<GameUser> getUser(@RequestParam(name = "username", required = false) String username) {
        // This returns a JSON or XML with the users

        return repository.findByUsername(username);
    }
}

